### ISSUE TITLE
组件独立使用的问题

### ISSUE THREAD

**Issue by z2n** [mix-php/database#2]
我用 `Swoole` 没有使用别的框架只想使用一个 `DB` 或 `orm` 库. 然后发现这个框架把组件都独立出来, 就尝试  `composer` 安装了这个. 可使用时发现依赖报错 (其他独立的组件好像也没在 `require` 声明依赖.). 而修复的方法似乎就还是会依赖框架.

有在不依赖 `mix/framework` 情况下使用这个组件方法吗?

**Comment by onanying** [comment]
mix前缀开头的，都无法独立，除了 mix-jsonrpc-client 外，多依赖一个 mix/framework 也没多大代码占用量，无防
